general {
   # lock_cmd = pidof hyprlock || hyprlock
   # before_sleep_cmd = hyprlock
   # after_sleep_cmd = hyprctl dispatch dpms on && brightnessctl -r
}

# 10 minutos
listener {
    timeout = 600
    on-timeout = brightnessctl -s set 0
    on-resume = brightnessctl -r
}

# 30 minutos hyprlock && 
listener {
    timeout = 1800
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 60 minutostrue
#listener {
#    timeout = 3600
#    on-timeout = systemctl suspend
#    on-resume = hyprctl dispatch dpms on && brightnessctl -r
#}
