exec-once = hyprpaper
exec-once = waybar
exec-once = hypridle
exec-once = nm-applet
exec-once = wl-paste --watch clipvault store
exec-once = swaync
exec-once = systemctl --user start hyprpolkitagent
exec-once = gnome-keyring-daemon --start --components=secrets
