# Hyprland environment variables

# --- XDG Desktop Portal ---
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# --- QT ---
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct   # Qt apps use qt6ct theme manager
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
# Forcing Qt dark theme (Breeze Dark or Kvantum dark theme in qt6ct)
env = QT_STYLE_OVERRIDE,BreezeDark

# --- GTK ---
env = GDK_SCALE,1
env = GTK_THEME,Tokyo-Night  # GTK apps dark theme
env = GTK_APPLICATION_PREFERS_DARK_THEME,1  # Force GTK dark

# --- Mozilla ---
env = MOZ_ENABLE_WAYLAND,1  # Force Firefox/Thunderbird to Wayland mode

# --- Ozone ---
env = ELECTRON_OZONE_PLATFORM_HINT,x11
env = ELECTRON_DISABLE_FRACTIONAL_SCALING,1

xwayland {
    force_zero_scaling = true
}

# --- For KVM virtual machines ---
# env = WLR_NO_HARDWARE_CURSORS, 1
# env = WLR_RENDERER_ALLOW_SOFTWARE, 1

# --- NVIDIA (optional) ---
#env = LIBVA_DRIVER_NAME,nvidia
# env = GBM_BACKEND,nvidia-drm
#env = __GLX_VENDOR_LIBRARY_NAME,nvidia
# env = __GL_VRR_ALLOWED,1
# env = WLR_DRM_NO_ATOMIC,1
