# See https://wiki.hyprland.org/Configuring/Monitors/
#monitor=,preferred,auto,1

# Lenovo Monitor
monitor = eDP-1, 1920x1080@60, 0x0, 1
monitor = HDMI-A-1, 1920x1080@60, auto-right, 0.8 

# Tv Sala
#monitor = eDP-1,1920x1080@144,0x0,1
#monitor = HDMI-A-1, 2560x1440@59.95, auto, 1
 
# Monitor Benq paraguay
#monitor = eDP-1, 1920x1080@144, 0x0, 1
#monitor = HDMI-A-1, 1920x1080@60, auto-left, 1  