# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# -------------------------------
# KITTY
# -------------------------------
windowrule {
  name = kitty-opacity
  match:class = kitty
  opacity = 1.0 override 0.7 override 0.8 override

}
# -------------------------------
# Visual code
# -------------------------------
windowrule {
  name = code-opacity
  match:class = code
  opacity = 0.96 override 0.8 override 0.8 override
}
# -------------------------------
# Thunar
# -------------------------------
windowrule {
  name = thunar-opacity
  match:class = thunar
  opacity = 0.90 override 0.8 override 0.8 override
}
