#!/usr/bin/env bash

dir="$HOME/.config/rofi/clipboard"
theme='style-clipboard'

# Run rofi dmenu with the clipboard theme
rofi_cmd() {
    rofi -dmenu \
        -display-columns 2 \
        -p "Clipboard" \
        -theme "${dir}/${theme}.rasi"
}

run() {
    # Show entries and capture selection
    selection=$(clipvault list | rofi_cmd)

    # If user selected something, copy it to clipboard
    if [[ -n "$selection" ]]; then
        clipvault get -- "$selection" | wl-copy
    fi
}

run
